name: CI
on:
  pull_request:
    branch: [develop]
  push:
    branch: [develop]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run format
      - run: npm test -- --coverage
        env:
          CI: true
      